version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/cinema/"
    schedule:
      interval: "monthly"
    groups:
      minor-bumps:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/cinema/"
    schedule:
      interval: "monthly"
    groups:
      minor-bumps:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pypi"
    directory: "/encode/"
    schedule:
      interval: "monthly"
    groups:
      minor-bumps:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
