version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/backend/"
    schedule:
      interval: "monthly"
    groups:
      minor-bumps:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "npm"
    directory: "/frontend/"
    schedule:
      interval: "monthly"
    groups:
      minor-bumps:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/encoder/"
    schedule:
      interval: "monthly"
    groups:
      minor-bumps:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
