name: MQTT

on:
  push:
    branches:
      - main
    paths:
      - "mqtt/**"
      - ".github/workflows/mqtt.yml"
  pull_request:
    paths:
      - "mqtt/**"
      - ".github/workflows/mqtt.yml"

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image (mqtt)
        uses: docker/build-push-action@v5
        with:
          context: ./mqtt
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: shish2k/cinema-mqtt:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - uses: shish/watchtower-update@main
        with:
          url: https://watchtower.shish.io/v1/update
          api_token: ${{ secrets.WATCHTOWER_TOKEN }}
          images: shish2k/cinema-mqtt
